### ISSUE TITLE
net70 support

### ISSUE THREAD

**Issue by jsandv** [jaredpar/basic-reference-assemblies#24]
Generate for net70

**Comment by jaredpar** [comment]
Will do this once `net7.0` RTMS. At the moment it's still in preview though.

**Comment by IvanJosipovic** [comment]
I would also appreciate having .net7 support even though it's in preview. RTM is expected in November, I expect release candidates shortly.

**Comment by jaredpar** [comment]
Once a RC is out I'll update the project.
