### ISSUE TITLE
Net60.csproj references preview version instead of stable

### ISSUE THREAD

**Issue by danielstreba** [jaredpar/basic-reference-assemblies#25]
Hello!

This csproj file is referencing an older preview version (6.0.0-preview.7.21377.19) of the Microsoft.NETCore.App.Ref instead of the latest stable version (6.0.5).

https://github.com/jaredpar/basic-reference-assemblies/blob/main/Basic.Reference.Assemblies.Net60/Basic.Reference.Assemblies.Net60.csproj

https://www.nuget.org/packages/Microsoft.NETCore.App.Ref/6.0.5

Is that any particular reason that an older version is used? Or the version number does not matter in this case?

**Comment by jaredpar** [comment]
Closing. I fixed this a bit ago but forgot to close this issue.
