### ISSUE TITLE
Missing ReferenceAssemblyKind.Net50

### ISSUE THREAD

**Issue by bernd5** [jaredpar/basic-reference-assemblies#36]
I have a project which uses `ReferenceAssemblyKind.Net50`.
In the current version it was removed (e.g. to remove the binary size...) - how should users query for net5.0?

**Comment by bernd5** [comment]
I got it: `comp.WithReferences(Net50.References.All)`.

In my eyes it would be better to introduce a new "SupportedOnly.BasicReferenceAssemblies".

**Comment by jaredpar** [comment]
> In my eyes it would be better to introduce a new "SupportedOnly.BasicReferenceAssemblies".

Not quite sure what you mean by this. Can you elaborate?

**Comment by bernd5** [comment]
I just mean that it would better to have a separate package which is smaller and contains only supported APIs instead of introducing a breaking change...
