### ISSUE TITLE
System.Text.Json

### ISSUE THREAD

**Issue by NeVeSpl** [jaredpar/basic-reference-assemblies#45]
Why `System.Text.Json.dll` reference assembly is not provided by this library? Is not it "basic" enough ?

**Comment by jaredpar** [comment]
The different reference sets here contain what a build gets by default when targeting the corresponding TFM. So the reference set provided by `NetStandard20` is the standard reference set you get when using `<TargetFramework>netstandard2.0</TargetFramework>` in a project file.

Not sure which reference set you're using here but you should see that `System.Text.Json` is available in the places it should be. For example it's not in `NetStandard20` but it is in `Net80`.

**Comment by NeVeSpl** [comment]
I am using `NetStandard20`, and was wondering what is the rule of selection references that are provided, but that explains everything. Switching to your library really helped with running code under different frameworks, and only reaming piece is System.Text.Json.dll (and its dependency Microsoft.Bcl.AsyncInterfaces.dll), but I can live with that and keep them in the resources.
