### ISSUE TITLE
Update for .NET 8 Release

### ISSUE THREAD

**Issue by agrittob** [jaredpar/basic-reference-assemblies#47]
Will there be an update that targets the final .NET 8 release in the near future?

**Comment by jaredpar** [comment]
I'll see if I can get that done sometime this week. Is there a particular reason you need 8.0 RTM? Some API that is missing / wrong?

**Comment by agrittob** [comment]
I am just updating an old tool that was full framework to using this library as it will make things easier, I just wasn't sure if the fact that it targeted the .NET 8 preview vs RTM release would be something to cause issues in use. Right now I have it targeting .NET 6 as that is what the old tool did as I make incremental updates to how it works.
