### ISSUE TITLE
The Net50 only nuget package doesn't have the ReferenceAssemblies.Net50 alias

### ISSUE THREAD

**Issue by belkiss** [jaredpar/basic-reference-assemblies#6]
Heya!

I was trying to move from the base package to the Basic.Reference.Assemblies.Net50 one, and had to change my code from using `Basic.Reference.Assemblies.ReferenceAssemblies.Net50` to `Basic.Reference.Assemblies.Net50.All`.

It's not a big deal, but would be nice to either add the alias or change the readme to document that in the https://github.com/jaredpar/basic-reference-assemblies#what-if-i-only-need-a-single-target-framework section.

Thanks!

**Comment by jaredpar** [comment]
Good point. That would make it simpler to jump back and forth between the packages.

**Comment by jaredpar** [comment]
Closing as the base package no longer has these references after #27 is complete.
