### ISSUE TITLE
Do I need all 163 references for basic compilation?

### ISSUE THREAD

**Issue by andrew-kuzovov** [jaredpar/basic-reference-assemblies#64]
Hi Jared,

At first, thanks for the helpful project!

It's more question than issue - is there minimal set of references (or can it be at all?)
In the `ReferenceAssemblies.Net80` I see many references that I won't need for basic compilation, like `Microsoft.VisualBasic...`, `System.Data...`, `System.Net...`

**Comment by jaredpar** [comment]
>  is there minimal set of references (or can it be at all?)

There certainly are ways to define more minimal sets but it's all about what do you want to do with them?  For example you could get the following to compile with significantly less references than the default. 

```csharp
using System;
Console.WriteLine("Hello World");
```

This requires that you define the scenarios, pretty concretely, and then identify all of the references necessary to make it work. There just aren't really any scenarios I've seen that are concretely defined and useful that it's worth adding other members besides `All`. Usually the scenarios are pretty customer specific and they can simply repackage the more minimal set in a helper inside their code. 

The reason that I have `All` is that it maps directly to what you get when you reference the corresponding TFM. That is a concrete scenario that will resonate with a lot of customers that want to compile code. Essentially this compiles with `<TargetFramework>net8.0</TargetFramework>` so give me the set of references that mimic that.

**Comment by andrew-kuzovov** [comment]
Got it, thanks!

Well, scenario is not to compile enterprise apps but simplest ones with basic types.

if `<TargetFramework>net8.0</TargetFramework>` really defines all these references then OK
